language: python
python:
- 3.7-dev
git:
  depth: false
addons:
  ssh_known_hosts:
  - proxy8.transport-intelligence.com:9022
  - 147.135.185.244:9022
before_script:
- echo -e "Host tiproxy8\n\tHostName ${TIPRX_SVR}\n\tPort ${TIPRX_PRT}\n\tForwardAgent yes\n\tStrictHostKeyChecking no" >> ~/.ssh/config
- echo -e "Host titsc\n\tHostName ${TITSC_SVR}\n\tProxyCommand ssh -W %h:22 qa@tiproxy8\n\tStrictHostKeyChecking no" >> ~/.ssh/config
- echo -e "Host titscnew\n\tHostName ${TITSCNEW_SVR}\n\tProxyCommand ssh -W %h:22 qa@tiproxy8\n\tStrictHostKeyChecking no" >> ~/.ssh/config
- openssl aes-256-cbc -K $encrypted_9b833f029019_key -iv $encrypted_9b833f029019_iv
  -in .travis/id_rsa.enc -out .travis/id_rsa -d
install:
- pip install -r ci-scripts/requirements.txt
script: /bin/sh .travis/hooks/all
script: /bin/bash ci-scripts/displayList.sh
before_deploy:
- openssl aes-256-cbc -K $encrypted_dd7324fa5dde_key -iv $encrypted_dd7324fa5dde_iv
  -in ci-scripts/id_rsa.travis-ci-deploy.enc -out /tmp/id_rsa.travis-ci-deploy -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/id_rsa.travis-ci-deploy
- ssh-add /tmp/id_rsa.travis-ci-deploy
deploy:
- provider: script
  skip_cleanup: true
  script: /bin/bash ci-scripts/deploy.sh
  on:
    branch: master

